import type { PixiPropertyTable } from "react-pixi-fiber";

export const properties: PixiPropertyTable = {
  boolean: [
    "applyAnchorToTexture",
    "cacheAsBitmap",
    "cullable",
    "cullableChildren",
    "interactiveChildren",
    "isRenderGroup",
    "renderable",
    "roundPixels",
    "sortableChildren",
    "uvRespectAnchor",
    "visible",
  ],
  callback: [
    "onclick",
    "onglobalmousemove",
    "onglobalpointermove",
    "onglobaltouchmove",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmouseupoutside",
    "onpointercancel",
    "onpointerdown",
    "onpointerenter",
    "onpointerleave",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointertap",
    "onpointerup",
    "onpointerupoutside",
    "onRender",
    "onrightclick",
    "onrightdown",
    "onrightup",
    "onrightupoutside",
    "ontap",
    "ontouchcancel",
    "ontouchend",
    "ontouchendoutside",
    "ontouchmove",
    "ontouchstart",
    "onwheel",
  ],
  numeric: ["angle", "clampMargin", "rotation", "x", "y", "zIndex"],
  // `tint` is not typed: PixiJS 8 also accepts a color string or array.
  positiveNumeric: ["alpha", "height", "resolution", "width"],
  untypedContainer: [
    "blendMode",
    "boundsArea",
    "cullArea",
    "cursor",
    "eventMode",
    "filterArea",
    "filters",
    "hitArea",
    "interactive",
    "label",
    "mask",
    "name",
    "origin",
    "sortDirty",
    "tint",
  ],
  vector: ["anchor", "pivot", "position", "scale", "skew", "tilePosition", "tileScale"],
};
