import type { PixiPropertyTable } from "react-pixi-fiber";

export const properties: PixiPropertyTable = {
  boolean: [
    "autoResize",
    "buttonMode",
    "cacheAsBitmap",
    "interactive",
    "interactiveChildren",
    "isMask",
    "nativeLines",
    "renderable",
    "roundPixels",
    "uvRespectAnchor",
    "visible",
  ],
  callback: [
    "added",
    "click",
    "mousedown",
    "mousemove",
    "mouseout",
    "mouseover",
    "mouseup",
    "mouseupoutside",
    "pointercancel",
    "pointerdown",
    "pointermove",
    "pointerout",
    "pointerover",
    "pointertap",
    "pointerup",
    "pointerupoutside",
    "removed",
    "rightclick",
    "rightdown",
    "rightup",
    "rightupoutside",
    "tap",
    "touchcancel",
    "touchend",
    "touchendoutside",
    "touchmove",
    "touchstart",
  ],
  numeric: ["boundsPadding", "clampMargin", "rotation", "x", "y"],
  positiveNumeric: ["alpha", "fillAlpha", "height", "lineColor", "maxWidth", "resolution", "tint", "width"],
  vector: ["anchor", "pivot", "position", "scale", "skew", "tilePosition", "tileScale"],
};
