import type { PixiPropertyTable } from "react-pixi-fiber";

export const properties: PixiPropertyTable = {
  boolean: [
    "autoResize",
    "buttonMode",
    "cacheAsBitmap",
    "interactive",
    "interactiveChildren",
    "isMask",
    "nativeLines",
    "renderable",
    "roundPixels",
    "uvRespectAnchor",
    "visible",
  ],
  callback: [
    "added",
    "click",
    "mousedown",
    "mousemove",
    "mouseout",
    "mouseover",
    "mouseup",
    "mouseupoutside",
    "onclick",
    "onglobalmousemove",
    "onglobalpointermove",
    "onglobaltouchmove",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmouseupoutside",
    "onpointercancel",
    "onpointerdown",
    "onpointerenter",
    "onpointerleave",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointertap",
    "onpointerup",
    "onpointerupoutside",
    "onrightclick",
    "onrightdown",
    "onrightup",
    "onrightupoutside",
    "ontap",
    "ontouchcancel",
    "ontouchend",
    "ontouchendoutside",
    "ontouchmove",
    "ontouchstart",
    "onwheel",
    "pointercancel",
    "pointerdown",
    "pointermove",
    "pointerout",
    "pointerover",
    "pointertap",
    "pointerup",
    "pointerupoutside",
    "removed",
    "rightclick",
    "rightdown",
    "rightup",
    "rightupoutside",
    "tap",
    "touchcancel",
    "touchend",
    "touchendoutside",
    "touchmove",
    "touchstart",
  ],
  numeric: ["boundsPadding", "clampMargin", "rotation", "x", "y"],
  positiveNumeric: ["alpha", "fillAlpha", "height", "lineColor", "maxWidth", "resolution", "width"],
  untypedContainer: [
    "angle",
    "cullable",
    "cullArea",
    "cursor",
    "eventMode",
    "filterArea",
    "filters",
    "hitArea",
    "mask",
    "name",
    "sortableChildren",
    "sortDirty",
    "transform",
    "zIndex",
  ],
  vector: ["anchor", "pivot", "position", "scale", "skew", "tilePosition", "tileScale"],
};
